# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dkdeploy documentation
email: opensource@dkd.de
description: dkdeploy documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dkdeploy.com" # the base hostname & protocol for your site
twitter_username: dkd_de
github_username:  dkdeploy
exclude: [foundation, vendor]
# Build settings
markdown: kramdown
algolia:
  application_id: 'QOFNLOOCWH'
  index_name:     'dkdeploy_production'
  record_css_selector: 'p,ul,td,th,h3,code'
